# Generated by Django 4.1.7 on 2024-01-24 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('integrationandOTVApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdverifierandnonce',
            name='timeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
