# Generated by Django 4.1.7 on 2024-01-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrationandOTVApp', '0005_alter_cdverifierandnonce_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdverifierandnonce',
            name='timeStamp',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
