# Generated by Django 4.1.7 on 2024-01-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrationandOTVApp', '0007_alter_cdverifierandnonce_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdverifierandnonce',
            name='timeStamp',
        ),
    ]
