# Generated by Django 4.1.7 on 2024-01-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrationandOTVApp', '0008_remove_cdverifierandnonce_timestamp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cdverifierandnonce',
            table='oidc_integration_python',
        ),
    ]
