# Generated by Django 4.1.7 on 2024-01-30 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrationandOTVApp', '0010_rename_cdverifierandnonce_oidc_integration_python_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='oidc_integration_python',
            new_name='CdVerifierAndNonce',
        ),
    ]
